### ISSUE TITLE
Error: Failed to mount SD card

### ISSUE THREAD

**Issue by danrlady** [AuroraWright/SafeA9LHInstaller#55]
When I try to install arm9loaderhax and press select, the following error appears: "failed to mount sd card". Everything worked properly up to this point and I do not know what else to do!  Apparently I am the only person on the internet with this problem.

I'm using a 4Gb SD Card

**Comment by RalphFox** [comment]
I'm was having the same issue too; My 3ds is the old 3ds xl, and the 3ds version was at 11.2.0.35U ; Everything was good until "installing-arm9loaderhax", when you navigate to 2xrsa site, after the screen glitching, and the a9lh app loading, when i press SELECT it shows "Error: failed to mount the SD card";

I tried the original 4gb card that comes with it(Lexar); This card didn't worked out; I used another card with 8gb, sandisk(with microsd to sd adapter) and it worked; maybe it's some sort of incompatibility?

Something strange is that i tried this in another old 3ds xl with  11.3 firmware and it worked 'out of the box'; It was the same brand, Lexar ; Maybe it is because of different manufacturer?(don't have the other 3ds to check the sdcard but this one is "made in korea";

Edit: Might as well as add to troubleshooting, "If error failed mount sdcard, then try another SD card"

**Comment by danrlady** [comment]
I solved the problem!

Copy the files on the sd card to a folder on you PC, format de SD Card (FAT 32) and move the files to the card again to continue the procedure from this point.
